name: Generate Keystore

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Store and Key Password (e.g., 123456 - Keep this safe!)'
        required: true
        default: '123456'

jobs:
  generate_keys:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create Keystore
        run: |
          keytool -genkey -v -keystore upload-keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias upload -storepass "${{ github.event.inputs.password }}" -keypass "${{ github.event.inputs.password }}" -dname "CN=ColorBlast, OU=Games, O=NecoYego, L=City, S=State, C=US"
          
      - name: Convert to Base64
        run: base64 upload-keystore.jks > keystore_base64.txt

      - name: Upload Base64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: keystore-base64-file
          path: keystore_base64.txt
